### ISSUE TITLE
[Bug]: Svg by name "circle-x" from set "fontawesome-regular" not found.

### ISSUE THREAD

**Issue by esghendry** [chrisreedio/socialment#48]
### What happened?

After encountering a login error, it appears that the following view is loaded:
.\vendor\chrisreedio\socialment\resources\views\login-error.blade.php
This view produces the error: "Svg by name "circle-x" from set "fontawesome-regular" not found."

### How to reproduce the bug

1. Add a new field to the User table, for example:
   ```php
   $table->uuid('uuid')->index();
   ```
2. Attempt to log in to the application.

3. The login process fails due to the changes made to the User table.

4. After the failed login, the user is redirected to the Filament admin login page:
   ```
   /admin/login
   ```
5. The error message "Svg by name "circle-x" from set "fontawesome-regular" not found" is displayed on the login error page.

### Package Version

3.6

### PHP Version

8.2.17

### Laravel Version

11.0.6

### Which operating systems does with happen with?

Windows

### Notes

I tried installing `blade-ui-kit/blade-icons` v1.6 and owenvoke/blade-fontawesome v2.6
It seems that the error is related to the Blade icon set "fontawesome-regular" and the specific icon "circle-x" not being found. This could be due to a missing or incorrect configuration of the Blade icon packages (`blade-ui-kit/blade-icons` and owenvoke/blade-fontawesome) in conjunction with the Socialment package. I have installed both.

**Comment by chrisreedio** [comment]
@esghendry great catch. 
This had popped up once before but it had slipped my mind.

I did not realize that font awesome had a pro AND a free version of this icon. 

I had accidentally used the pro version instead of the free. 

I had expected far more icons to be used from FA which is why I originally included it. 

Working to just swap to hero icons for this.

**Comment by chrisreedio** [comment]
I didn't end up switching to a heroicon version. 

Looks like there are two versions of this icon that are nearly identical in name.
The linked PR swaps out the Pro version for the free one.

When signed into FA, it hides the 'Pro' label so they look the same.

Logged out:
![image](https://github.com/chrisreedio/socialment/assets/77644584/5c0b4c19-dea1-4a0b-8404-c048a5733b15)

Logged in:
![image](https://github.com/chrisreedio/socialment/assets/77644584/f1160a6f-3d5f-4742-86eb-17c557e35caa)

I'll try to keep this in mind in the future.

**Comment by chrisreedio** [comment]
This has been fixed in [v3.6.1](https://github.com/chrisreedio/socialment/releases/tag/v3.6.1) that was just released.
